# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class UiMainWindow(object):
    def setup_ui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(436, 227)
        MainWindow.setMinimumSize(QtCore.QSize(436, 227))
        MainWindow.setMaximumSize(QtCore.QSize(436, 227))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(436, 226))
        self.centralwidget.setMaximumSize(QtCore.QSize(436, 226))
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 441, 261))
        self.tabWidget.setMaximumSize(QtCore.QSize(671, 421))
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.encrypt_tab = QtWidgets.QWidget()
        self.encrypt_tab.setObjectName("encrypt_tab")
        self.pushButton = QtWidgets.QPushButton(self.encrypt_tab)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.pushButton.setObjectName("pushButton")
        self.text_input = QtWidgets.QTextEdit(self.encrypt_tab)
        self.text_input.setGeometry(QtCore.QRect(120, 10, 301, 161))
        self.text_input.setObjectName("text_input")
        self.Debug_area_1 = QtWidgets.QLineEdit(self.encrypt_tab)
        self.Debug_area_1.setGeometry(QtCore.QRect(0, 180, 431, 20))
        self.Debug_area_1.setFrame(False)
        self.Debug_area_1.setReadOnly(True)
        self.Debug_area_1.setObjectName("Debug_area_1")
        self.lineEdit = QtWidgets.QLineEdit(self.encrypt_tab)
        self.lineEdit.setGeometry(QtCore.QRect(10, 50, 91, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_4 = QtWidgets.QPushButton(self.encrypt_tab)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 130, 91, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidget.addTab(self.encrypt_tab, "")
        self.decrypt_tab = QtWidgets.QWidget()
        self.decrypt_tab.setObjectName("decrypt_tab")
        self.pushButton_2 = QtWidgets.QPushButton(self.decrypt_tab)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 91, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.text_output = QtWidgets.QTextEdit(self.decrypt_tab)
        self.text_output.setGeometry(QtCore.QRect(120, 10, 301, 161))
        self.text_output.setReadOnly(True)
        self.text_output.setObjectName("text_output")
        self.Debug_area_2 = QtWidgets.QLineEdit(self.decrypt_tab)
        self.Debug_area_2.setGeometry(QtCore.QRect(0, 180, 431, 20))
        self.Debug_area_2.setFrame(False)
        self.Debug_area_2.setReadOnly(True)
        self.Debug_area_2.setObjectName("Debug_area_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.decrypt_tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 50, 91, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.decrypt_tab)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 130, 91, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox = QtWidgets.QCheckBox(self.decrypt_tab)
        self.checkBox.setGeometry(QtCore.QRect(10, 160, 101, 17))
        self.checkBox.setObjectName("checkBox")
        self.tabWidget.addTab(self.decrypt_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateui(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateui(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("CryptoImage", "CryptoImage"))
        self.pushButton.setText(_translate("MainWindow", "Load Image"))
        self.text_input.setPlaceholderText(_translate("MainWindow", "Input text"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Input key..."))
        self.pushButton_4.setText(_translate("MainWindow", "Encrypt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.encrypt_tab), _translate("MainWindow", "Encrypt"))
        self.pushButton_2.setText(_translate("MainWindow", "Load Image"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Input key..."))
        self.pushButton_3.setText(_translate("MainWindow", "Decrypt"))
        self.checkBox.setText(_translate("MainWindow", "Save to res.txt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.decrypt_tab), _translate("MainWindow", "Decrypt"))
